module.exports = {
  WEEKS_IN_SEASON: 10,
  MAPS: ['Rush', 'Iron', 'Emerald', 'Velocity', 'Transilio', 'Smirk', 'Pilot', 'Constriction', 'Community', 'Wormy', 'Rush'],
  KEYS: ['s9abab',
  's9abab_m',
  's9bcbc',
  's9bcbc_m',
  's9cdcd',
  's9cdcd_m',
  's9dede',
  's9dede_m',
  's9efef',
  's9efef_m',
  's9fgfg',
  's9fgfg_m',
  's9ghgh',
  's9ghgh_m',
  's9hihi',
  's9hihi_m',
  's9ijij',
  's9ijij_m',
  's9jkjk',
  's9jkjk_m',
  's9klkl',
  's9klkl_m',
  's9lmlm',
  's9lmlm_m',
  's9mnmn',
  's9mnmn_m',
  's9nono',
  's9nono_m',
  's9opop',
  's9opop_m',
  's9pqpq',
  's9pqpq_m'],
  MLTP_TEAMS: [
  	{
  		name: "Ghostboosters",
  		minorsName: "qakboosters",
  		key: "s9abab",
  		captain: "Fronj",
  		roster: ['Gem','swerve','quarky.','Eashy','Jake from SF','ProTagonist_','TheAprilFool','Sneak','FLYMOLO','Heisy','MrFruitzy','Catalyst'],
  		schedule: ['Dyson Majors', 'Adrenaline Spikes', 'KGBallers', 'Base Gods', 'LagProne', 'Dyson Majors', 'ALL CAPS', 'KGBallers', 'Boostin Dynamo', 'LagProne'],
  		server: "Radius",
  		division: "Atlantic"
  	},
  	{
  		name: "Dyson Majors",
  		minorsName: "Dyson Minors",
  		key: "s9bcbc",
  		captain: "GriefSeeds",
  		roster: ['Lej','CHECKNATE','SirDan','Brake','InTents','Pebble.','CB13','Schwedd','Mactheroni','Jmart','bowtie','mudrat'],
  		schedule: ['Ghostboosters', 'Base Gods', 'LagProne', 'ALL CAPS', 'KGBallers', 'Ghostboosters', 'Boostin Dynamo', 'LagProne', 'Adrenaline Spikes', 'KGBallers'],
  		server: "Radius",
  		division: "Atlantic"
  	},
  	{
  		name: "KGBallers",
  		minorsName: "FSBallers",
  		key: "s9cdcd",
  		captain: "Stalin",
  		roster: ['i\'m high','Stann','Ball OON','have mad','Ess','CamWatts','Billdacat','Yakkit','Hom','Bob Loblaw','Elegant','Howard'],
  		schedule: ['LagProne', 'ALL CAPS', 'Ghostboosters', 'Boostin Dynamo', 'Dyson Majors', 'LagProne', 'Adrenaline Spikes', 'Ghostboosters', 'Base Gods', 'Dyson Majors'],
  		server: "Pi",
  		division: "Atlantic"
  	},
  	{
  		name: "LagProne",
  		minorsName: "LagProne",
  		key: "s9dede",
  		captain: "Ballymandias",
  		roster: ['LEBRON*JAMES','Turbo','RemoSlice','YS1','Gman8181','HarkMollis','Adam_Bomb','E','Envy','ludifisk','OJDude','chelseafc'],
  		schedule: ['KGBallers', 'Boostin Dynamo', 'Dyson Majors', 'Adrenaline Spikes', 'Ghostboosters', 'KGBallers', 'Base Gods', 'Dyson Majors', 'ALL CAPS', 'Ghostboosters'],
  		server: "Pi",
  		division: "Atlantic"
  	},
  	{
  		name: "Boostin Dynamo",
  		minorsName: "Boostin Dynamo",
  		key: "s9efef",
  		captain: "jjpoole",
  		roster: ['Risk','Matetricks','Sherrattinho','C Bivvey','Vials','intercest','Zvonvok','bigbadball','kutrebar','Sam-','Knox.','Dusk'],
  		schedule: ['ALL CAPS', 'LagProne', 'Base Gods', 'KGBallers', 'Adrenaline Spikes', 'ALL CAPS', 'Dyson Majors', 'Base Gods', 'Ghostboosters', 'Adrenaline Spikes'],
  		server: "Radius",
  		division: "Northeast"
  	},
  	{
  		name: "ALL CAPS",
  		minorsName: "SMALL CAPS",
  		key: "s9fgfg",
  		captain: "BALLDONTLIE",
  		roster: ['HULZY','EAGLES.','FAT','SYNIIKAL','EBOLA','ASHMUNGASHMA','DEATH PICKLE','CHRISBALL','VEEZY','LU','FUCKING LAG','ODD'],
  		schedule: ['Boostin Dynamo', 'KGBallers', 'Adrenaline Spikes', 'Dyson Majors', 'Base Gods', 'Boostin Dynamo', 'Ghostboosters', 'Adrenaline Spikes', 'LagProne', 'Base Gods'],
  		server: "Radius",
  		division: "Northeast"
  	},
  	{
  		name: "Adrenaline Spikes",
  		minorsName: "Adrenaline Boosts",
  		key: "s9ghgh",
  		captain: "Nebuchanezar",
  		roster: ['Romulus','Russia\'','Prizm','Dennit','TagUpTurnUp','SuperSans','SpaceTiger','Ajax.','Bongo','Mufro','The Tyrant','Koala King'],
  		schedule: ['Base Gods', 'Ghostboosters', 'ALL CAPS', 'LagProne', 'Boostin Dynamo', 'Base Gods', 'KGBallers', 'ALL CAPS', 'Dyson Majors', 'Boostin Dynamo'],
  		server: "Radius",
  		division: "Northeast"
  	},
  	{
  		name: "Base Gods",
  		minorsName: "The Pack",
  		key: "s9hihi",
  		captain: "Raven",
  		roster: ['Mr.Gone','bdl','jj\'s pool','fuckingtank','Armbranch','iAaronK','Punster','odawg','MrJoeHobo','derds','canniba||','Gyaraderp'],
  		schedule: ['Adrenaline Spikes', 'Dyson Majors', 'Boostin Dynamo', 'Ghostboosters', 'ALL CAPS', 'Adrenaline Spikes', 'LagProne' , 'Boostin Dynamo', 'KGBallers', 'ALL CAPS'],
  		server: "Radius",
  		division: "Northeast"
  	},
  	{
  		name: "Origin Ducks",
  		minorsName: "The Okay Hens",
  		key: "s9ijij",
  		captain: "okthen",
  		roster: ['Crippy','Ty','donuts42','aardvark74','Ball God','Bal McCartny','Blue Dream','Abe Lincoln','fxu','BG','MeaL','Snack'],
  		schedule: ["Merballs", "Angry Balls Redux", "Tears", "Texas Hold'em", "BMX2: Electric Ballaloo", "Merballs", "Roll Models", "Tears", "Holdin' Gate Warriors", "BMX2: Electric Ballaloo"],
  		server: "Origin",
  		division: "Central"
  	},
  	{
  		name: "Tears",
  		minorsName: "Orzaballs",
  		key: "s9jkjk",
  		captain: "TroBall",
  		roster: ['Fatal', 'AnnaKendrick','DudeMcGuy','mathnasium','Frozty','fucking owen','coys','NEUhusky','wabi-sabi','JBaayBaay','mahatma','Jet2','alchemist'],
  		schedule: ["BMX2: Electric Ballaloo", "Roll Models", "Origin Ducks", "Holdin' Gate Warriors", "Merballs", "BMX2: Electric Ballaloo", "Angry Balls Redux", "Origin Ducks", "Texas Hold'em", "Merballs"],
  		server: "Origin",
  		division: "Central"
  	},
  	{
  		name: "Merballs",
  		minorsName: "Little Merballs",
  		key: "s9klkl",
  		captain: "KPow",
  		roster: ['Dino', 'Legman','Mr. Hat','Jay','Arbybear','oh_snap!','Fuzz Ball','Snowball','MANIAC!!!!!!','dat cap','danisk','Kitten Panda','Gubbles'],
  		schedule: ["Origin Ducks", "Texas Hold'em", "BMX2: Electric Ballaloo", "Roll Models", "Tears", "Origin Ducks", "Holdin' Gate Warriors", "BMX2: Electric Ballaloo", "Angry Balls Redux", "Tears"],
  		server: "Origin",
  		division: "Central"
  	},
  	{
  		name: "BMX2: Electric Ballaloo",
  		minorsName: "EZ eees",
  		key: "s9lmlm",
  		captain: "BAllstar",
  		roster: ['lukemoo','eee','bad','F2PDynasty','quibble','ASS CANNON','saundy','Kimba','superdiglett','Esoog','Micaso','WowSuchPro'],
  		schedule: ["Tears", "Holdin' Gate Warriors", "Merballs", "Angry Balls Redux", "Origin Ducks", "Tears", "Texas Hold'em", "Merballs", "Roll Models", "Origin Ducks"],
  		server: "Origin",
  		division: "Central"
  	},
  	{
  		name: "Texas Hold'em",
  		minorsName: "Texas Hold'em",
  		key: "s9mnmn",
  		captain: "Dalek",
  		roster: ['Altiger','SIDE','yank','ooo kill \'em','Legion','Team','Ralph Wiggum','Chalksy','timeboy','MATOI RYUKO','Dodge','RoboPop_'],
  		schedule: ["Angry Balls Redux", "Merballs", "Holdin' Gate Warriors", "Origin Ducks", "Roll Models", "Angry Balls Redux", "BMX2: Electric Ballaloo", "Holdin' Gate Warriors", "Tears", "Roll Models"],
  		server: "Sphere",
  		division: "Pacific"
  	},
  	{
  		name: "Holdin' Gate Warriors",
  		minorsName: "Holdin' Gate Warriors",
  		key: "s9nono",
  		captain: "Curry",
  		roster: ['Ibis','dodsfall','bigbird','Manbear','NotPrey','Iron_Ball','lolugrumpy','APthatsME.','MEGATRON','Mr Bucket','elfitzo','abcd'],
  		schedule: ["Roll Models", "BMX2: Electric Ballaloo", "Texas Hold'em", "Tears", "Angry Balls Redux", "Roll Models", "Merballs", "Texas Hold'em", "Origin Ducks", "Angry Balls Redux"],
  		server: "Centra",
  		division: "Pacific"
  	},
  	{
  		name: "Angry Balls Redux",
  		minorsName: "Angry Balls Redux",
  		key: "s9opop",
  		captain: "Spiller",
  		roster: ['bluemonday','ooo killem','UnoriginalSN','alvin','Wayne','Eggo','Fowlball','simon','Ballzilla','Ball-E','Sun Chips','P K Subball'],
  		schedule: ["Texas Hold'em", "Origin Ducks", "Roll Models", "BMX2: Electric Ballaloo", "Holdin' Gate Warriors", "Texas Hold'em", "Tears", "Roll Models", "Merballs", "Holdin' Gate Warriors"],
  		server: "Centra",
  		division: "Pacific"
  	},
  	{
  		name: "Roll Models",
  		minorsName: "Roll Models",
  		key: "s9pqpq",
  		captain: "Sundown",
  		roster: ['dywz','Apopalypse','Koala','Ignitius','Skinny Chode','Pnaoxt','PrivateMajor','El Sacko','Asa Akira','MKo','B.I.G.Money'],
  		schedule: ["Holdin' Gate Warriors", "Tears", "Angry Balls Redux", "Merballs", "Texas Hold'em", "Holdin' Gate Warriors", "Origin Ducks", "Angry Balls Redux", "BMX2: Electric Ballaloo", "Texas Hold'em"],
  		server: "Centra",
  		division: "Pacific"
  	},
  ]
};
